public class Main {
    public static void main(String[] args) {
        var cat = 3.6;
        var dog = 8.0;
        var paper = 763789;
        System.out.println(cat);
        System.out.println(dog);
        System.out.println(paper);
        cat = cat + 4;
        dog = dog + 4;
        paper = paper + 4;
        System.out.println(cat);
        System.out.println(dog);
        System.out.println(paper);
        cat = cat - 1.6;
        dog = dog - 3.5;
        paper = paper - 7639;
        System.out.println(cat);
        System.out.println(dog);
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var firstBoxerWeight = 78.2;
        var secondBoxerWeight = 82.7;
        var totalWeight = firstBoxerWeight + secondBoxerWeight;
        System.out.println("Общий вес " + totalWeight);
        var weightDifference = secondBoxerWeight - firstBoxerWeight;
        System.out.println("Разница " + weightDifference);
        var remains = secondBoxerWeight % firstBoxerWeight;
        System.out.println("Остаток " + remains);
        var totalHours = 640;
        var eachWorkerWorkTime = 8;
        var totalWorkers = totalHours / eachWorkerWorkTime;
        System.out.println("Всего работников в компании - " + totalWorkers + " человек");
        totalWorkers = totalWorkers + 94;
        System.out.println("Если в компании работает " + totalWorkers + " человек, то всего " + totalWorkers * 8 + " часов работы может быть поделено между сотрудниками");
    }
}